
MODELS_DIR_NAME = "models"
MODEL_PATH = "models.pt"
RESULTS_PATH = "models/results.txt"

VALID_FILE_EXTENSIONS = ['.jpg', '.jpeg', '.png', '.gif', '.bmp', '.tiff']

# TRAINING SETTINGS
NUM_EPOCHS = 5

# LEARNING RATE SETTINGS
BASE_LR = 0.00001
DECAY_WEIGHT = 0.1 
EPOCH_DECAY = 30 

# DATASET INFO
NUM_CLASSES = 2

# DATALOADER PROPERTIES
BATCH_SIZE = 64
NUM_WORKERS = 8

# GUI
DEFAULT_IMAGE_FILE = "images/default.jpeg"
